# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputwindow.ui',
# licensing of 'inputwindow.ui' applies.
#
# Created: Wed Jun 19 15:33:20 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_InputWindow(object):
    def setupUi(self, InputWindow):
        InputWindow.setObjectName("InputWindow")
        InputWindow.resize(471, 588)
        self.centralWidget = QtWidgets.QWidget(InputWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 411, 441))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setContentsMargins(5, 0, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.OutputFormat = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OutputFormat.setFont(font)
        self.OutputFormat.setObjectName("OutputFormat")
        self.gridLayout.addWidget(self.OutputFormat, 8, 0, 1, 1)
        self.Width_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Width_input.setObjectName("Width_input")
        self.gridLayout.addWidget(self.Width_input, 5, 2, 1, 1)
        self.GUID_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.GUID_input.setText("")
        self.GUID_input.setObjectName("GUID_input")
        self.gridLayout.addWidget(self.GUID_input, 4, 2, 1, 1)
        self.Height_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Height_input.setObjectName("Height_input")
        self.gridLayout.addWidget(self.Height_input, 7, 2, 1, 1)
        self.Width = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Width.setFont(font)
        self.Width.setObjectName("Width")
        self.gridLayout.addWidget(self.Width, 5, 0, 1, 1)
        self.Component = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Component.setFont(font)
        self.Component.setObjectName("Component")
        self.gridLayout.addWidget(self.Component, 3, 0, 1, 1)
        self.InputPath = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.InputPath.setFont(font)
        self.InputPath.setObjectName("InputPath")
        self.gridLayout.addWidget(self.InputPath, 1, 0, 1, 1)
        self.OutputFormat_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.OutputFormat_input.setObjectName("OutputFormat_input")
        self.gridLayout.addWidget(self.OutputFormat_input, 8, 2, 1, 1)
        self.Component_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Component_input.setObjectName("Component_input")
        self.gridLayout.addWidget(self.Component_input, 3, 2, 1, 1)
        self.GUID = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GUID.setFont(font)
        self.GUID.setObjectName("GUID")
        self.gridLayout.addWidget(self.GUID, 4, 0, 1, 1)
        self.InputPathText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.InputPathText.setObjectName("InputPathText")
        self.gridLayout.addWidget(self.InputPathText, 1, 2, 1, 1)
        self.SelectPath = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SelectPath.setObjectName("SelectPath")
        self.gridLayout.addWidget(self.SelectPath, 1, 3, 1, 1)
        self.Height = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Height.setFont(font)
        self.Height.setObjectName("Height")
        self.gridLayout.addWidget(self.Height, 7, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralWidget)
        self.buttonBox.setGeometry(QtCore.QRect(130, 490, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        InputWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(InputWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 471, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuInput = QtWidgets.QMenu(self.menuBar)
        self.menuInput.setObjectName("menuInput")
        InputWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(InputWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        InputWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.menuBar.addAction(self.menuInput.menuAction())

        self.retranslateUi(InputWindow)
        QtCore.QMetaObject.connectSlotsByName(InputWindow)

    def retranslateUi(self, InputWindow):
        InputWindow.setWindowTitle(QtWidgets.QApplication.translate("InputWindow", "InputWindow", None, -1))
        self.OutputFormat.setText(QtWidgets.QApplication.translate("InputWindow", "Output Format", None, -1))
        self.Width.setText(QtWidgets.QApplication.translate("InputWindow", "Width", None, -1))
        self.Component.setText(QtWidgets.QApplication.translate("InputWindow", "Componet", None, -1))
        self.InputPath.setText(QtWidgets.QApplication.translate("InputWindow", "Input Path", None, -1))
        self.GUID.setText(QtWidgets.QApplication.translate("InputWindow", "GUID", None, -1))
        self.SelectPath.setText(QtWidgets.QApplication.translate("InputWindow", "Select Path", None, -1))
        self.Height.setText(QtWidgets.QApplication.translate("InputWindow", "Height", None, -1))
        self.menuInput.setTitle(QtWidgets.QApplication.translate("InputWindow", "Input", None, -1))

